Financial-Times/n-teaser

- README.md
- demos/index.html
- demos/script.js
- demos/style.css
- templates/opinion.mustache
We've been making progress with the templating work. We're kind of struck around `n-card`, as we don't want to use it - it's mighty and very difficult to port to Handlebars/ES6 template strings.
I'm suggesting that, for now, we just create two Handlebars templates (opinion & article) from `o-card` and put them in a new `n-teaser`.  Then over time we all can update/replace these as we make progress.
> a very basic setup, by no means the final setup

- templates/extra-light.html
- templates/heavy.html
- templates/light.html
- templates/standard.html
myFT links use the `referrerTracking` property to append query-string params/hashes to article URLs.
/cc @adgad
> Add `referrerTracking` (& some data-trackables)

- data_model/fragments.js
- main.js
- package.json
In building the data model for the n-teaser, it became pretty obvious that the model is tied to the template.
So I thought it would be an idea to have these data query fragments hosted in the n-teaser.
They can then be imported by any client app that wants to extract data for for presentation in a teaser.
This means that any changes to the template and data model can be done in one module together and propagated easily, without having to do releases of each client app.
However it does mean that it needs to be an NPM module to enable the requiring of the data fragments.
Client app would do;
`const fragments = require(n-teaser).fragments` or
`import {fragments} from n-teaser` for the hipsters.
> Add: data model query fragments

- data_model/fragments.js
tells us whether a piece of content is of genre opinion to be used for styling color of tag.
> Add: isOpinion to data fragments for light teaser

- data_model/fragments.js
To make the shorter (promotional) title available to n-teasers
> Add: promotional title to data fragments

- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
For some headshots, especially those with very light hair or high
contrast, this tinting param makes the head appear like a set of
floating eyes.
I sat down with Sue and we found a better color which means even people
with very light hair photographed at high contrast can still be made
out.
Before:
After (tested with all headshots)
> Fix tinting

- templates/partials/display-tag.html
- templates/partials/related-content.html
cc: @keirog 
In some views, eg. front page big story, there is a need to suppress certain standard template features (eg. tag or related content).
In pre v1.0.0 these were done by setting tag or relatedContent to false. However in the new presenter model the data no longer works in a way that is compatible with that.
Hence partials will take arguments of noTag or noRelatedContent to suppress those elements from presentation.
> Amend: allow pass through of display parameters to templates

- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
Editorial request for when a piece of content is an opinion piece and has a brand, that it should display the brand as the genre prefix and the author as the main (clickable tag).
Examples;
> Amend: display tag logic for author & brand combos

- src/data-model/fragments.js
Otherwise it just links to the home page when we have the brand author combo.
> Fix: pass relativeUrl through for author tags

- templates/partials/display-tag.html
Taking the genre prefix in the display tag out of the topic link.
> Amend: split genre prefix away from tag link

- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
it removes the headshot already, but also needs to remove the class.
> Amend: remove headshot class when noHeadshot attribute passed

- templates/partials/image.html
- templates/partials/main-image.html
@i-like-robots @lc512k 
Addresses issue in DAC report issue tracking document:
```
DAC-USER-KO-T10-05
Science and Environment
Images getting focus where they shouldn’t or should have a focus ring, as user tabs through stories
```
While we have the headline (which links to the same place), there does not seem to be any purpose in having tab focus on the image as well, so have opted for the former of the suggestions, but am happy to be proven wrong with exceptions.
> Prevent: Tab focus on images

- src/presenters/teaser-presenter.js
- templates/extra-light.html
- templates/heavy.html
- templates/lifestyle.html
- templates/light.html
- templates/partials/title.html
- templates/standard.html
- templates/top-story-heavy.html
- templates/top-story-standard.html
- tests/presenters/teaser-presenter.spec.js
can use flag `teaserUsePromotionalTitle` to toggle between shorter promotional title and standard title in headline across all teasers across the site.
> Enhancement: enable toggle between promotional and standard title

- templates/partials/standfirst.html
- templates/partials/title.html
Fixes a bug where the title and standfirst on a related article card would double encode the ampersand from `&` > `&amp;` > `&amp;amp;`. Which would render as `&amp;` in the browser
> don't escape characters in the title and standfirst

- src/presenters/teaser-presenter.js
- templates/partials/headshot.html
- tests/presenters/teaser-presenter.spec.js
@andygnewman 
This is _sooo_ hacky. I reckon a new major version of n-image will be in order soon (loads of react stuff to remove anyway) and fixing
- tight coupling of lazy loading & responsiveness with n-image base classes
- not all properties always get propagated through the image presenter and on to the template (e.g. width/height)
But for now, it fixes a perf regression on the home page, so would still like to get this out and raise a tech debt issue
> lazy loading headshots

- src/presenters/teaser-presenter.js
This allows the Top Stories teaser to have no related content links
(for example, if they are not part of the Graph-QL query).
@andygnewman @adgad
> Don't barf when no related content

- src/presenters/teaser-presenter.js
- templates/partials/display-tag.html
- tests/presenters/teaser-presenter.spec.js
Currently both paid posts and promoted content share the same prefix of 'by' between the label and the advertiser name.
There is a business requirement for the promoted content to have a prefix of 'paid for by', where as paid post should retain the 'by' prefix.
Have implemented the logic for this in the presenter rather than the template.
> Amend: Promoted content prefix

- .pa11yci.js
Pa11y Screenshots helped us realize we'd been passing the viewport wrong all along (all screenshots were coming out at the default size of 1024x768)
Fixed now for n-teaser. Will propagate to https://github.com/Financial-Times/n-makefile/blob/master/config/.pa11yci.js for `next-` apps
cc @rowanmanning
> fix viewports

- bower.json
- demos/src/demo.scss
- package.json
cc @laurieboyes @debugwand @keirog, I've removed n-ui and swapped out for n-ui-foundations. Demos look fine and pa11y tests still run. I'm not entirely familiar with n-teaser, though, would you mind giving it a sanity check? Anything else need updating?
> update and remove n-ui

- demos/fixtures/fixtures.json
- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- tests/fixtures/article-brand-fixture.json
- tests/fixtures/article-opinion-author-fixture.json
- tests/fixtures/article-standard-fixture.json
- tests/presenters/teaser-presenter.spec.js
I'll merge this into the `migrate_v2` branch once I get my next-api build passing.
(note: things might break in the transition)
> Story package => Curated related content

- src/data-model/fragments.js
- src/presenters/package-teaser-presenter.js
- src/presenters/teaser-presenter.js
- templates/extra-light.html
- tests/fixtures/article-brand-fixture.json
- tests/fixtures/article-opinion-author-fixture.json
- tests/fixtures/article-package-fixture.json
- tests/fixtures/article-standard-fixture.json
- tests/fixtures/package-fixture.json
- tests/presenters/package-teaser-presenter.spec.js
- tests/presenters/teaser-presenter.spec.js
* Authors now returns an `author` concept (which has the headshot deets)
* a `Brand` can't be a `Person`, so remove code around getting the brand's headshot
> Use new genre, brand and authors next-api fields

- templates/partials/title.html
this will be used by the new syndication logic; and will eventually allow us to remove, from `n-teaser`, some of the syndication logic currently contained in there.
> Adding article's content ID as `[data-content-id]` 

- bower.json
This was causing styling issues downstream.
Before:
After:
🐿 v2.5.16
> Un-dev bower dependencies

- src/presenters/teaser-presenter.js
We have a need for this on myFT because the markup created on the
client side and we don't want to also have to initalise o-video.
This is tied to [this PR in the front page ](https://github.com/Financial-Times/next-front-page/pull/1669)
> Allow teasers to disable the insitu playable video

- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
Should be able to tidy this up by removing all the `contentPackageTitle` stuff once we confirm the new one is working.
Also see https://github.com/Financial-Times/next-api/pull/355
and https://github.com/Financial-Times/next-es-interface/pull/1035
> Add new headline variant field

- secrets.js
- src/presenters/teaser-presenter.js
🐿 v2.5.16
[Trello ticket](https://trello.com/c/nM0QFnwz/744-expose-explainer-in-a-genre-on-teasers)
This change prefixes the story title with 'Explainer' prefix:
> Show genre label for 'Explainer' stories

- demos/fixtures/fixtures-video.json
- src/presenters/teaser-presenter.js
- tests/fixtures/video-fixture.json
- tests/presenters/teaser-presenter.spec.js
Fix a bug which is not displayed video prefix
https://trello.com/c/xsscnimq/44-video-teasers-on-stream-page-arent-showing-the-video-label
> modify content.type Video => video

- src/presenters/teaser-presenter.js
🐿 v2.6.0
add `toLowerCase()` to check video type because content.type from next-api is `Video` but content.type from next-elastic is `video` .
> add toLowerCase to check video type

- src/presenters/teaser-presenter.js
- templates/partials/timestamp.html
- tests/presenters/teaser-presenter.spec.js
a performance tweak...
don't render the timestamp if it's older than 4 hours, as it will then get hidden client-side (by o-date JS) anyway
this is behind the flag `perfDate2` for A/B testing to see for any movement with metrics
> don't render dead timestamps

- templates/heavy.html
to more closely resemble that of CSS, to avoid a brief shifting of
elements when CSS is slow
> image before content

- src/data-model/es.js
This PR contains one of the changes needed to display a "Premium" label in the onward journey of articles.
`next-lure-api` gets a list of ElasticSearch fields from `n-teaser` and it uses it to build a query to the `next-api`. The problem is that this list contains fields that are not used in ElasticSearch, and `premium` is one of those.
We deemed this change to be safe as nothing else seems to be importing the file `data-model/es.js`.
The argument for leaving the name of this file the way it is, is that `next-api` is supposed to be phased out.
[Trello card](https://trello.com/c/xSMx0SDp/777-add-premium-label-on-the-read-next-story-teasers)
🐿 v2.8.0
> Add accessLevel to ElasticSearch field list

- src/data-model/es.js
This change will make the lure-api return an extra `type` field that will let next-article know whether a teaser should be presented as a video (or possibly something else).
At the moment this is not going to cause any visible change in the onward journey or the ribbon, but I still believe that the "type" field needs to be returned, so that if someone makes changes to the way `o-teaser` displays videos, their changes will be reflected.
P.S.: Hope it makes sense!
🐿 v2.8.0
> Adding "type" field to ElasticSearch model

- templates/partials/main-image.html
A low vision user reported "There was an image link at the top right of the page, which on mouse hover did not respond with any descriptive label. The only audible response was a URL. "
This provides an alt text description for users who do this, whilst also keeping it hidden from screenreader users as this would be a duplicate link for them.
Tested in Voiceover, JAWS, NVDA
🐿 v2.8.0
> Add alt text for low-vision users

- templates/partials/main-image.html
Reverts Financial-Times/n-teaser#179
https://financialtimes.slack.com/archives/C2LMEKC6S/p1522252186000176?thread_ts=1522248481.000017&cid=C2LMEKC6S
> in this case it is the title for the low-vision users who are perceiving that there is a link there and need to know what it links to. It gets hidden from pretty much everyone else. Descriptive text would not help in this case as the user must be able to pick out “here is a link, where will it go
> Revert "Use a better source of data for img alt attributes"

- secrets.js
- src/presenters/teaser-presenter.js
This is a temporary fix because now loads of stories will be FastFT because that's how they started out life. However the articles receive subsequent edits and are not really "fast" anymore. The proper fix is modelling this some how in UPP... so just 🌀waiting for that.
Also, only display the author when there's only one author.
> Disallow FastFT in meta tag 

- src/presenters/teaser-presenter.js
- templates/partials/title.html
The Origami team had created a special class in `o-teaser` to enable us to A/B test the use of a [different shade of black](https://trello.com/c/A1NSJYFR/769-visited-stories) for visited links.
Visited link colours are normally changed using the `:visited` pseudo-selector but that's not suitable for A/B tests.
The test has now been successful, so the "experimental" class [has now been removed](https://github.com/Financial-Times/o-teaser/pull/94) from `o-teaser`.
This PR simply reflects that change in `n-teaser`.
Once this is merged, I wil delete the flag.
> Remove `visitedStoriesOnTeaser` flag

- README.md
- secret-squirrel.js
- src/presenters/teaser-presenter.js
- templates/partials/timestamp.html
An opportunity to change the `data-o-date-format` property in the teaser timestamp by passing an argument `dataDateFormat`.
> Option to change data-o-date-format in timestamp

- src/presenters/teaser-presenter.js
we're restructuring the perfJanky flag to have 3 variants, and we want this performance optimisation to happen with just the 'calm' variant
> accommodate de-janky flag restructure

- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
Reverts Financial-Times/n-teaser#196
Because people are unsure about what they want and they are angry about it
> Revert "Use promotional standfirst"

- demos/fixtures/fixures-live-blog-closed.json
- demos/fixtures/fixures-live-blog.json
- src/data-model/es.js
- src/data-model/fragments.js
- tests/fixtures/article-brand-fixture.json
- tests/fixtures/article-opinion-author-fixture.json
- tests/fixtures/article-package-fixture.json
- tests/fixtures/article-standard-fixture.json
- tests/fixtures/video-es-fixture.json
- tests/fixtures/video-fixture.json
If the GraphQL query doesn't pull in `displayConcept.isDisplayTag` then that data isn't available as part of the diffing logic that is used to purge the front-page. Which means the front page doesn't get purged properly.
> Add displayConcept.isDisplayTag to GraphQL queries and test fixtures

- package.json
- src/presenters/teaser-presenter.js
- templates/partials/title.html
- tests/presenters/teaser-presenter.spec.js
Works in conjunction with n-ui changes to support tracking of multiple teasers on homepage with variant headlines configured: https://github.com/Financial-Times/n-ui/pull/1364/
> Teaser testing

- bower.json
- src/presenters/teaser-presenter.js
- templates/partials/main-image.html
- templates/partials/title.html
- tests/presenters/teaser-presenter.spec.js
This is part of fixing DAC issues.
Issue
----
Tab focus is not visible on Video image links present under 'Video' heading link.
(Keyboard only users issue)
Solution suggested by DAC
----
Provide a visible outline/border to each interactive element on the page when they receives focus, using CSS.
**However,** it won't be good for Screen reader users if we added the focus outline because
Redundant links should not be provided, as it will be time consuming for the user to navigate to the same link.(image and title link lead to the same page.)
So I'm going to apply no-tabbing for the image links to solve for both users. 
----
Tab focus is not visible on Video image links present under 'Video' heading link.
> Apply no tabbing for video image links

- bower.json
- templates/partials/title.html
o-labels 4 has a breaking change in that uses a different classname for premium labels.
https://github.com/Financial-Times/o-labels/blob/master/MIGRATION.md#migrating-from-v3-to-v4
This will be released as a new major version to clearly describe the change.
🐿 v2.12.4
> Render premium labels in an o-labels v4 compatible way

- templates/partials/display-concept.html
so that the screen reader is slightly more verbose about where, for example, the link `Argentina` leads us, we now give it an aria-label which will say 'link, Category: Argentina'.  This should make it clearer that the link takes you to `ft.com/argentina`
🐿 v2.12.4
> add aria label for categories

- tests/presenters/teaser-presenter.spec.js
The `teaserUsePromotionalTitle` flag  is no longer used so this test can be safely deleted 🐿 v2.12.4
> remove reference to teaserUsePromotionalTitle flag in tests
