- bower.json
- demos/index.html
- demos/script.js
- demos/style.css
- templates/landscape.mustache
Along with various lint fixes
(still to do: we need to add n.Makefile, linters, verify task & get this on CircleCI)
> add landscape template and set as a bower project

- .gitignore
- bower.json
- templates/extra-light.html
- templates/heavy.html
- templates/landscape.html
- templates/light.html
- templates/opinion.html
- templates/standard.html
Easier to work on during the early days
> Move the latest n-teaser work into master

- templates/light.html
> Prepare for myFT page usage

- templates/light.html
> Rename tags to singular tag, for consistency with 90% of use-cases

- templates/heavy.html
- templates/standard.html
[PR#8](https://github.com/Financial-Times/n-teaser/pull/8)
> Reflect changes in PR#8

- templates/extra-light.html
- templates/heavy.html
- templates/light.html
- templates/standard.html
> Add headshots

- templates/heavy.html
- templates/light.html
- templates/standard.html
- templates/top-story.html
> Paid posts

- bower.json
> Switch to non-adam branch while he’s away

- data_model/fragments.js
redo fragments to align with new definitions of teaser templates
> Add: update query fragments for new templates

- templates/heavy.html
- templates/light.html
- templates/partials/meta.html
- templates/standard.html
- templates/top-story-heavy.html
- templates/top-story-standard.html
I've done this using what (I think) is the new data model so I can use it for special report ads...don't think genre is readily available from what I can tell in the old model...
> Add genre tag

- templates/heavy.html
- templates/top-story-heavy.html
> Add links to images

- bower.json
> Point to the non-non-adam branch of o-teaser

- templates/extra-light.html
- templates/heavy.html
- templates/light.html
- templates/standard.html
- templates/top-story-heavy.html
- templates/top-story-standard.html
> Allow html in headlines because editorial

- templates/top-story-heavy.html
- templates/top-story-standard.html
> Add opinion class to top story templates

- templates/extra-light.html
- templates/heavy.html
- templates/light.html
- templates/partials/heading.html
- templates/standard.html
- templates/top-story-heavy.html
- templates/top-story-standard.html
> Move headings out into its own partial

- bower.json
- templates/partials/heading.html
> Add premium labels to teaser headlines

- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- templates/partials/display-tag.html
> Add duration to heavy template

- templates/partials/display-tag.html
> Amend: put display tag in span for managing break

- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- src/utils/hyphenate-pascal-case.js
- tests/presenters/teaser-presenter.spec.js
- tests/utils/hyphenate-pascal-case.spec.js
> Add 'type' of content as a modifier

- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
Was using incorrect data structure for liveblogs.
> Fix: liveblog time stamp

- src/presenters/teaser-presenter.js
- templates/partials/display-tag.html
- tests/presenters/teaser-presenter.spec.js
> Add: live blog label to tag

- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
Add headshots when there is an author brand combo tag
> Add: headshots shown when author brand combo tag

- src/presenters/teaser-presenter.js
- templates/partials/heading.html
- templates/partials/related-content.html
- tests/presenters/teaser-presenter.spec.js
> Output 'type' of related content modifier

- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
Improve the logic around deduping the display tag vs the stream tag.
> Amend: improve stream id display tag deduping

- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
hero-image attributes of opinion and highlights are not required for hero-image
> Amend: Clean up hero image when has other attributes

- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
Remove special report genre tag from display tag on special report pages
> Amend: remove genre tag on special report pages

- Makefile
- README.md
- bower.json
- demos/app.js
- demos/demo.html
- demos/fixtures.json
- demos/src/demo.scss
- package.json
- templates/partials/main-image.html
> Add demo server and some demos

- .pa11yci.js
- Makefile
- demos/app.js
- package.json
> Add pa11y to the CI pipeline

- demos/fixtures.json
- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
> add flag to denote potential syndication

- templates/partials/title.html
> remove h3 from teasers

- templates/partials/title.html
> Add a class for the front-page video player to hook onto

- templates/partials/main-image.html
> Add another hook to indicate external JS reliance on this element

- README.md
Addresses: https://github.com/Financial-Times/next-a11y/issues/71.
> Add: Demo page + Pa11y notes to README

- src/data-model/fragments.js
> corrected graphQL fragments

- src/data-model/fragments.js
> Y GRAPHQL?? 

- src/presenters/package-teaser-presenter.js
- templates/partials/package-content.html
- tests/presenters/package-teaser-presenter.spec.js
> shows special report in tag

- src/presenters/package-teaser-presenter.js
- src/presenters/teaser-presenter.js
- tests/fixtures/article-brand-fixture.json
- tests/fixtures/article-standard-fixture.json
- tests/fixtures/package-fixture.json
- tests/presenters/package-teaser-presenter.spec.js
- tests/presenters/teaser-presenter.spec.js
> fix: brand => brandConcpet

- src/data-model/fragments.js
- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
> Adding extra headline for headline a/b testing

- src/data-model/fragments.js
> Apply alternative headline ability to all teasers

- circle.yml
Reverts Financial-Times/n-teaser#130
No `make deploy` for components 😴☕️
> Revert "Add deploy-by-day"

- package.json
- src/presenters/teaser-presenter.js
- templates/partials/main-image.html
- templates/partials/title.html
> Add data-trackable to teaser for headline testing

- src/presenters/teaser-presenter.js
> Remove the test that never was

- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
> Headlines fixes

- templates/partials/main-image.html
- templates/partials/title.html
> Data trackable fix

- src/presenters/teaser-presenter.js
- templates/partials/headshot.html
- tests/presenters/teaser-presenter.spec.js
> Remove alt tag from headshots for a11y

- src/presenters/teaser-presenter.js
- tests/presenters/teaser-presenter.spec.js
So that we can override the default blue for the myFT homepage component.
It's so beautiful 😭  
🐿 v2.5.16
> Allow for custom headshot tint

- src/presenters/package-teaser-presenter.js
- tests/presenters/package-teaser-presenter.spec.js
This should hopefully fix the broken teasers here www.ft.com/career
🐿 v2.5.16
> Add displayImage and displayStandfirst to package teaser presenter

- src/presenters/teaser-presenter.js
fix for https://sentry.io/nextftcom/ft-next-article/issues/396541023/
> fix genreConcept from es

- main.js
- src/data-model/es.js
> added es-based data model

- src/presenters/teaser-presenter.js
Currently throwing an error on frontpage, probably due to an empty liveblog.
🐿 v2.5.16
> Check liveblog updates is an array first

- src/presenters/teaser-presenter.js
- templates/partials/title.html
Blocked by this PR: https://github.com/Financial-Times/o-teaser/pull/84
[Trello](https://trello.com/c/A1NSJYFR/769-visited-stories-mvt)
> Class for visited links

- secrets.js
- src/presenters/teaser-presenter.js
> Update Opinion UUID

- templates/heavy.html
This reverts commit 2e7ed2632a7e73ad06183ebc391e40f8e0c9e22a.
> Revert "image before content rather than image after content (#170)"

- src/presenters/teaser-presenter.js
> add a `perfJanky` flag for collective janky testing

- templates/partials/headshot.html
https://trello.com/c/gDN6YdG0/2-dactechimagesissue01-dactechimagesissue02
https://www.w3.org/TR/WCAG20-TECHS/H67.html#H67-description
> Add empty alt attribute to headshots

- demos/fixtures/fixtures-video.json
- demos/templates/demo.html
- secret-squirrel.js
- src/presenters/teaser-presenter.js
- templates/partials/main-image.html
- tests/presenters/teaser-presenter.spec.js
This helps with users navigating the site using their voice and expecting the play icon to be navigable.
> Include a aria-label for video teasers

- templates/partials/main-image.html
> DAC-user-lv-zk-t1-03 Swap alt to title

- templates/partials/main-image.html
Reverts Financial-Times/n-teaser#181
> Revert "DAC-user-lv-zk-t1-03 Swap alt to title"

- templates/partials/main-image.html
> Put title on to anchor

- package.json
> Update mocha to mitigate a security issue in growl and minimatch deps

- templates/partials/main-image.html
- templates/partials/standfirst.html
- templates/partials/title.html
> Escape html in title and standfirsts

- .pa11yci.js
- package.json
- src/presenters/teaser-presenter.js
> Remove old flag

- src/presenters/package-teaser-presenter.js
- src/presenters/teaser-presenter.js
- tests/presenters/package-teaser-presenter.spec.js
- tests/presenters/teaser-presenter.spec.js
remove teaserUsePromotionalTitle flag
This behaviour will switch to permanently enabled
> remove teaserUsePromotionalTitle flag
